apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: $app_name
  name: $app_name
  namespace: $namespace
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: $app_name
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: snapshot-promoter 
